import type {
  ExportOptions,
  Skin,
} from "./types";

function getMimeType(
  format: ExportOptions["format"]
): string {
  switch (format) {
    case "jpeg":
      return "image/jpeg";

    case "webp":
      return "image/webp";

    case "png":
    default:
      return "image/png";
  }
}

function canvasToBlob(
  canvas: HTMLCanvasElement,
  mimeType: string,
  quality: number
): Promise<Blob> {
  return new Promise((resolve, reject) => {
    canvas.toBlob(
      (blob) => {
        if (!blob) {
          reject(
            new Error(
              "The browser could not create the exported image."
            )
          );

          return;
        }

        resolve(blob);
      },
      mimeType,
      quality
    );
  });
}

export async function exportCollage(
  skins: Skin[],
  options: ExportOptions
): Promise<Blob> {
  if (!skins.length) {
    throw new Error(
      "There are no detected items to export."
    );
  }

  const {
    width,
    columns,
    gap,
    padding,
    background,
    format,
    quality,
  } = options;

  if (width <= 0) {
    throw new Error(
      "Export width must be greater than zero."
    );
  }

  if (columns <= 0) {
    throw new Error(
      "Columns must be greater than zero."
    );
  }

  const firstImage =
    skins[0].image;

  if (!firstImage.naturalWidth) {
    throw new Error(
      "The source image has not finished loading."
    );
  }

  /*
   * Each detected item keeps the crop coordinates
   * generated by image.ts.
   *
   * sx/sy are the source coordinates.
   * The source crop width/height are calculated
   * from the detection data when available.
   */

  const sourceWidth =
    firstImage.naturalWidth;

  const sourceHeight =
    firstImage.naturalHeight;

  /*
   * Use a square-ish cell based on the source
   * screenshot. This keeps the collage consistent.
   */
  const cellAspect =
    sourceWidth / Math.max(1, sourceHeight);

  const cellWidth =
    Math.max(
      1,
      Math.floor(
        (width -
          padding * 2 -
          gap * (columns - 1)) /
          columns
      )
    );

  const cellHeight =
    Math.max(
      1,
      Math.round(
        cellWidth / cellAspect
      )
    );

  const rows =
    Math.ceil(
      skins.length / columns
    );

  const height =
    padding * 2 +
    rows * cellHeight +
    Math.max(
      0,
      rows - 1
    ) * gap;

  const canvas =
    document.createElement("canvas");

  canvas.width = width;
  canvas.height = height;

  const context =
    canvas.getContext("2d", {
      alpha: false,
    });

  if (!context) {
    throw new Error(
      "Your browser does not support canvas rendering."
    );
  }

  context.imageSmoothingEnabled = true;
  context.imageSmoothingQuality =
    "high";

  context.fillStyle = background;
  context.fillRect(
    0,
    0,
    width,
    height
  );

  skins.forEach((skin, index) => {
    const column =
      index % columns;

    const row =
      Math.floor(index / columns);

    const dx =
      padding +
      column *
        (cellWidth + gap);

    const dy =
      padding +
      row *
        (cellHeight + gap);

    const image =
      skin.image;

    /*
     * The detected crop uses sx/sy as its
     * starting point.
     *
     * If the crop extends outside the image,
     * clamp it safely.
     */
    const sx =
      Math.max(
        0,
        Math.min(
          image.naturalWidth - 1,
          skin.sx
        )
      );

    const sy =
      Math.max(
        0,
        Math.min(
          image.naturalHeight - 1,
          skin.sy
        )
      );

    const availableWidth =
      image.naturalWidth - sx;

    const availableHeight =
      image.naturalHeight - sy;

    const sw =
      Math.max(
        1,
        Math.min(
          availableWidth,
          Math.round(
            availableHeight *
              cellAspect
          )
        )
      );

    const sh =
      Math.max(
        1,
        Math.min(
          availableHeight,
          Math.round(
            sw / cellAspect
          )
        )
      );

    context.drawImage(
      image,
      sx,
      sy,
      sw,
      sh,
      dx,
      dy,
      cellWidth,
      cellHeight
    );
  });

  return canvasToBlob(
    canvas,
    getMimeType(format),
    quality
  );
}

export function downloadBlob(
  blob: Blob,
  filename: string
): void {
  const url =
    URL.createObjectURL(blob);

  const anchor =
    document.createElement("a");

  anchor.href = url;
  anchor.download = filename;

  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();

  window.setTimeout(() => {
    URL.revokeObjectURL(url);
  }, 1000);
}
